In [ ]:
'''
基本的数学还是要掌握的
初级阶段先没有必要系统的学习数学的理论知识


非结构的数据的处理


四中模型：
分类预测，回归模型，聚类模型，时间序列
逻辑回归LR（logisticsRegression），kmeans(聚类) 朴素贝叶斯（）
人工神经网络（）
逻辑回归的知识点，数学理论知识

手动实现逻辑回归代码，了解算法的原理（后期要这样做）


PCA 主成分分析 数据降维

'''
'''
数据足够多，大数据时代
算法的发展比较成熟
计算机硬件设备的提高

AI领域里的机器学习

DeepLearning
Deeplearning 的基础是 人工神经网络

机器学习：机器学习是AI的一种，给计算机提供一种能力，这种能力不需要编程去实现
由机器学习生成的模型自动去学习，去判断 去识别

训练模型，

'''
'''
一般分为训练集和测试集
训练集：带有样本标签，确定当前样本中N个特征的 标签是什么
测试集：通过已有的训练集 以及 训练集的标签，生成的模型去预测 测试集中的样本的标签

把数据扔到模型里面去学习，学的是里面的参数

同一个模型是不同的模型
同一个模型 读取的数据不同，那么生成的模型也是不同的

'''
'''
训练样本进来后，通过我们设置的参数等，然后通过第一次学习拿到预测值，
获取到的预测值会跟真实值之间有一些差别，（因为在训练，所以会有真实值）
预测的标签和训练集样本的标签有误差

更新权重去减少误差
把误差减少的最少的时候模型就是最好的模型

'''
'''
机器学习的框架
第一步：建立一堆的模型 建立一堆的函数，不同参数的组合，构成不同的模型，，

第二步：定义一个度量来衡量模型的好坏，看模型预测好坏 通过 度量的 标准，然后读取数据

第三部：根据标准在数据上面选一个更好方法模型或者函数出来

'''
'''
除了算法和模型以外
还有特征这一块
降维
模型筛选
特征的预处理
交叉验证
'''
'''
监督学习 训练样本包含对应的标签，如识别问题

无监督学习 训练样本不包含对应的标签 如聚类

将原始数据集分为：

训练集、验证集、测试集
训练集：训练模型
验证集：做交叉验证，选一些参数，选一些超参数，如随机森林的参数等
由自己去定义的参数，调参，选择超参数，
测试集：用训练好的模型去做预测，内部预测

'''

'''
训练集上训练模型，fit
predict() 预测模型

dump 保存模型

维度即特征


'''

In [3]:
from sklearn import datasets
#鸢尾花
iris = datasets.load_iris()
#手写数字识别 
digits = datasets.load_digits()

In [4]:
print(iris.data)
#代表有150个样本，它的特征维度为4
print(iris.data.shape)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
#打印标签名称 三种标签，分别为
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [6]:
#将标签字符串 对应成数字
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
#手写数字图片的维度
#图片是8*8 的 用skImage读取进内存时 就是8*8的矩阵
#标签是一维向量，没有列
'''
大写的X代表是一个矩阵
小写Y代表一个向量

当我们在初始化模型的的时候 手动写入的参数就是超参数，这些参数是不能通过学习得到的

SVM模型在学习的时候，模型内部有很多参数要学习，这些参数让模型自动去学习就可以啦


超参数和模型里面要学习的参数不同，

训练时：让模型对象fit,fit(样本的特征，相对应的样本的标签)

'''

'''
查看结果，accuracy_score
预测标签和真实标签

 
生产环节 不可能 每次都要训练模型

将模型保存下来，下次默认加载
通过pickle 保存pickle.dump()模型

with open('svm_model.pkl','wb') as f:
    pickle.dump(svm_model,f)

with open('svm_model.pkl','rb') as f:
    model = pickle.load(f)



直接预测
后期直接通过model.predict(random_samples)


准备数据集：
数据处理，特征工程，训练集、测试集分割

特征工程 不同行业领域的特征都不同，比较复杂

文本数据分析

100维特征中：哪些是好的，哪些是不好，是否有冗余的

PCA：


生产环境中不太可能去重新生成模型，在模型中去调整超参数

如何调整超参数？
1、根据经验调整超参数
2、通过交叉验证调整最优参数

行数为样本数
列数是特征维度

首先进行数据处理
二位数组：形状（样本数，特征维度）

np.reshape()转化数据集维度


'''


'''
特征归一化
平米数/2000
特征归一化之后 效果 会特别好，学习时间变短，模型的效果也比较好

为什么要进行特征归一化：
1、引入归一化，是由于在不同评价指标（特征指标）中，其量纲或是量纲单位往往不同，
变化区间处于不同的数量级，若不进行归一化，可能导致某些指标被忽视，影响到数据分析的结果。

2、为了消除特征数据之间的量纲影响，需要进行归一化处理，以解决特征指标之间的可比性。
原始数据经过归一化处理后，各指标处于同一数量级，以便进行综合对比评价。

例：
房间的平米数：70 80 100
房间的卧室个数：2 3 4
卧室和房间比例向
如果不做任何的处理，扰动就比较大，训练学习的时间比较长，模型的效果也不好

此时要把特征归一化进同一个区域，归一化到[0,1]
结果是学习时间变短，模型效果也比较好

#######################
梯度下降，损失值越小

Python进行不平衡数据处理

特征归一化不是对样本，是对一列操作的
一行中样本有不同的特征，一列是特征
特征归一化是对一列

先向量化特征还是应该先筛选变量？
没有规定的步骤
先向量化，去做筛选

一定要把数据转换为numpy数组
random_state 确保每次随机分割得到相同的结果
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=1/3,random_state=7)



'''
'''
归一化：
preprocessing.scale(X)
preprocessing 有中心归一化，最大最小归一化

特征的维度没有变化，只是范围改变，只是在范围上进行了缩放
'''
'''

X,y =make_classification()


svm_classifier.fit(X_train, y_train)
svm_classifier.score(X_test,y_test)

特征归一化很有必要，提升模型的预测度，由50% 提升至90%
'''
'''
样本数大于50
是否预测一个类？类上面是否有标签？（有监督学习还是无监督学习）
若数量小于100K 使用线性SVC，大于100k 使用随机梯度下降
文本数据使用朴素贝叶斯，非文本数据使用K近邻
或者在使用随机森林



聚类模型：
Kmeans：
GMM（高斯混合模型）：


Regression

PCA 数据降维（主成分分析）
'''
'''
训练的对象：
Estimator 对象

fit方法训练Estimator
get_params() 返回模型之前定义的参数
score() 对 Estimator进行评分
回归模型：使用 决定系数 评分
分类模型：使用 准确率 评分
'''
'''
连续的标签 要使用 回归模型

获取数据集=特征处理完毕之后
-------
1、初始化模型
2、数据集进行拆分（分割数据集，测试集）
3、训练模型 .fit(X_train, y_train )
模型训练完毕之后，使用模型.get_params()//获取参数
#返回参数
lr_model.get_params()返回参数
#训练集上的预测
lr_model.score(X_train, y_train)
#0.7596
#测试集上的预测
lr_model.score(X_test, y_test)
#0.6698
'''

'''
交叉验证调整参数、调整超参数
cross valation (CV)
在训练集中进行交叉验证
10折的交叉验证

C = 1 的时候做10轮
将训练集分为10等分
拿出第1份当做验证集，剩余9份做验证
拿出第2份当做验证集，剩余9份做验证
拿出第3份当做验证集，剩余9份做验证
拿出第...份当做验证集，剩余9份做验证

交叉完毕之后，拿到10次验证获取到的值得平均值

C = 2 的时候再做10轮
....
C = 10 的时候在做10轮

使用K近邻的例子演示交叉验证的方式

01：35：14
'''


